package com.github.kisaragieffective.kisaragistd.function

import com.github.kisaragieffective.kisaragistd.annotations.AutoGenerated

fun <T1, Q> ((T1) -> Q).currying(): (T1) -> Q {
    return this
}

@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, Q> ((T1, T2) -> Q).currying(): (T1) -> (T2) -> Q {
    return { t1 ->
        { t2 ->
            this@currying(t1, t2)
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, Q> ((T1, T2, T3) -> Q).currying(): (T1) -> (T2) -> (T3) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                this@currying(t1, t2, t3)
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, Q> ((T1, T2, T3, T4) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    this@currying(t1, t2, t3, t4)
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, Q> ((T1, T2, T3, T4, T5) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        this@currying(t1, t2, t3, t4, t5)
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, Q> ((T1, T2, T3, T4, T5, T6) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            this@currying(t1, t2, t3, t4, t5, t6)
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, Q> ((T1, T2, T3, T4, T5, T6, T7) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                this@currying(t1, t2, t3, t4, t5, t6, t7)
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, Q> ((T1, T2, T3, T4, T5, T6, T7, T8) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    this@currying(t1, t2, t3, t4, t5, t6, t7, t8)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11)
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12)
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13)
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14)
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15)
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16)
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17)
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> (T18) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        { t18 ->
                                                                            this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18)
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> (T18) -> (T19) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        { t18 ->
                                                                            { t19 ->
                                                                                this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19)
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> (T18) -> (T19) -> (T20) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        { t18 ->
                                                                            { t19 ->
                                                                                { t20 ->
                                                                                    this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20)
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> (T18) -> (T19) -> (T20) -> (T21) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        { t18 ->
                                                                            { t19 ->
                                                                                { t20 ->
                                                                                    { t21 ->
                                                                                        this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21)
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
@AutoGenerated("CurriedFunctionGenerator.kts")
fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, Q> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) -> Q).currying(): (T1) -> (T2) -> (T3) -> (T4) -> (T5) -> (T6) -> (T7) -> (T8) -> (T9) -> (T10) -> (T11) -> (T12) -> (T13) -> (T14) -> (T15) -> (T16) -> (T17) -> (T18) -> (T19) -> (T20) -> (T21) -> (T22) -> Q {
    return { t1 ->
        { t2 ->
            { t3 ->
                { t4 ->
                    { t5 ->
                        { t6 ->
                            { t7 ->
                                { t8 ->
                                    { t9 ->
                                        { t10 ->
                                            { t11 ->
                                                { t12 ->
                                                    { t13 ->
                                                        { t14 ->
                                                            { t15 ->
                                                                { t16 ->
                                                                    { t17 ->
                                                                        { t18 ->
                                                                            { t19 ->
                                                                                { t20 ->
                                                                                    { t21 ->
                                                                                        { t22 ->
                                                                                            this@currying(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22)
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
