for (i in 1..5) {
    println("""@AutoGenerated("ClasslessCollectionFactory_enumSetOf")""")
    println("fun <E : Enum<E>> enumSetOf(" + (1..i).joinToString { "e$it: E" } + "): EnumSet<E> {")
    println("    return EnumSet.of(" + (1..i).joinToString { "e$it" } + ")")
    println("}")
    println()
}