@file:AutoGenerated("DestructionValueProtocolGenerator")
package com.github.kisaragieffective.kisaragistd.valuedestruction

import com.github.kisaragieffective.kisaragistd.AutoGenerated

interface DestructionValueProtocol

interface DestructionValueProtocol1<E1> : DestructionValueProtocol {
    fun component1(): E1
}

interface DestructionValueProtocol2<E1, E2> : DestructionValueProtocol1<E1> {
    fun component2(): E2
}

interface DestructionValueProtocol3<E1, E2, E3> : DestructionValueProtocol2<E1, E2> {
    fun component3(): E3
}

interface DestructionValueProtocol4<E1, E2, E3, E4> : DestructionValueProtocol3<E1, E2, E3> {
    fun component4(): E4
}

interface DestructionValueProtocol5<E1, E2, E3, E4, E5> : DestructionValueProtocol4<E1, E2, E3, E4> {
    fun component5(): E5
}

interface DestructionValueProtocol6<E1, E2, E3, E4, E5, E6> : DestructionValueProtocol5<E1, E2, E3, E4, E5> {
    fun component6(): E6
}

interface DestructionValueProtocol7<E1, E2, E3, E4, E5, E6, E7> : DestructionValueProtocol6<E1, E2, E3, E4, E5, E6> {
    fun component7(): E7
}

interface DestructionValueProtocol8<E1, E2, E3, E4, E5, E6, E7, E8> : DestructionValueProtocol7<E1, E2, E3, E4, E5, E6, E7> {
    fun component8(): E8
}

interface DestructionValueProtocol9<E1, E2, E3, E4, E5, E6, E7, E8, E9> : DestructionValueProtocol8<E1, E2, E3, E4, E5, E6, E7, E8> {
    fun component9(): E9
}

interface DestructionValueProtocol10<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10> : DestructionValueProtocol9<E1, E2, E3, E4, E5, E6, E7, E8, E9> {
    fun component10(): E10
}

interface DestructionValueProtocol11<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11> : DestructionValueProtocol10<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10> {
    fun component11(): E11
}

interface DestructionValueProtocol12<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12> : DestructionValueProtocol11<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11> {
    fun component12(): E12
}

interface DestructionValueProtocol13<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13> : DestructionValueProtocol12<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12> {
    fun component13(): E13
}

interface DestructionValueProtocol14<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14> : DestructionValueProtocol13<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13> {
    fun component14(): E14
}

interface DestructionValueProtocol15<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15> : DestructionValueProtocol14<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14> {
    fun component15(): E15
}

interface DestructionValueProtocol16<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16> : DestructionValueProtocol15<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15> {
    fun component16(): E16
}

interface DestructionValueProtocol17<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17> : DestructionValueProtocol16<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16> {
    fun component17(): E17
}

interface DestructionValueProtocol18<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18> : DestructionValueProtocol17<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17> {
    fun component18(): E18
}

interface DestructionValueProtocol19<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19> : DestructionValueProtocol18<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18> {
    fun component19(): E19
}

interface DestructionValueProtocol20<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20> : DestructionValueProtocol19<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19> {
    fun component20(): E20
}

interface DestructionValueProtocol21<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21> : DestructionValueProtocol20<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20> {
    fun component21(): E21
}

interface DestructionValueProtocol22<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22> : DestructionValueProtocol21<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21> {
    fun component22(): E22
}

interface DestructionValueProtocol23<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23> : DestructionValueProtocol22<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22> {
    fun component23(): E23
}

interface DestructionValueProtocol24<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24> : DestructionValueProtocol23<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23> {
    fun component24(): E24
}

interface DestructionValueProtocol25<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25> : DestructionValueProtocol24<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24> {
    fun component25(): E25
}

interface DestructionValueProtocol26<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26> : DestructionValueProtocol25<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25> {
    fun component26(): E26
}

interface DestructionValueProtocol27<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27> : DestructionValueProtocol26<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26> {
    fun component27(): E27
}

interface DestructionValueProtocol28<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28> : DestructionValueProtocol27<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27> {
    fun component28(): E28
}

interface DestructionValueProtocol29<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29> : DestructionValueProtocol28<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28> {
    fun component29(): E29
}

interface DestructionValueProtocol30<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30> : DestructionValueProtocol29<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29> {
    fun component30(): E30
}

interface DestructionValueProtocol31<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31> : DestructionValueProtocol30<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30> {
    fun component31(): E31
}

interface DestructionValueProtocol32<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31, E32> : DestructionValueProtocol31<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31> {
    fun component32(): E32
}