package com.github.kisaragieffective.kisaragistd.annotations

/**
 * If element annotated with this, you'll have to modify the base script, not them.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FILE, AnnotationTarget.FUNCTION)
annotation class AutoGenerated(val fileName: String)