@file:AutoGenerated("DestructionValueProtocolGenerator")
package com.github.kisaragieffective.kisaragistd.collection.valuedestruction

import com.github.kisaragieffective.kisaragistd.annotations.AutoGenerated

interface DestructionValueProtocol

interface DestructionValueProtocol1<out E1> : DestructionValueProtocol {
    fun component1(): E1
}

interface DestructionValueProtocol2<out E1, out E2> : DestructionValueProtocol1<E1> {
    fun component2(): E2
}

interface DestructionValueProtocol3<out E1, out E2, out E3> : DestructionValueProtocol2<E1, E2> {
    fun component3(): E3
}

interface DestructionValueProtocol4<out E1, out E2, out E3, out E4> : DestructionValueProtocol3<E1, E2, E3> {
    fun component4(): E4
}

interface DestructionValueProtocol5<out E1, out E2, out E3, out E4, out E5> : DestructionValueProtocol4<E1, E2, E3, E4> {
    fun component5(): E5
}

interface DestructionValueProtocol6<out E1, out E2, out E3, out E4, out E5, out E6> : DestructionValueProtocol5<E1, E2, E3, E4, E5> {
    fun component6(): E6
}

interface DestructionValueProtocol7<out E1, out E2, out E3, out E4, out E5, out E6, out E7> : DestructionValueProtocol6<E1, E2, E3, E4, E5, E6> {
    fun component7(): E7
}

interface DestructionValueProtocol8<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8> : DestructionValueProtocol7<E1, E2, E3, E4, E5, E6, E7> {
    fun component8(): E8
}

interface DestructionValueProtocol9<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9> : DestructionValueProtocol8<E1, E2, E3, E4, E5, E6, E7, E8> {
    fun component9(): E9
}

interface DestructionValueProtocol10<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10> : DestructionValueProtocol9<E1, E2, E3, E4, E5, E6, E7, E8, E9> {
    fun component10(): E10
}

interface DestructionValueProtocol11<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11> : DestructionValueProtocol10<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10> {
    fun component11(): E11
}

interface DestructionValueProtocol12<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12> : DestructionValueProtocol11<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11> {
    fun component12(): E12
}

interface DestructionValueProtocol13<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13> : DestructionValueProtocol12<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12> {
    fun component13(): E13
}

interface DestructionValueProtocol14<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14> : DestructionValueProtocol13<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13> {
    fun component14(): E14
}

interface DestructionValueProtocol15<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15> : DestructionValueProtocol14<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14> {
    fun component15(): E15
}

interface DestructionValueProtocol16<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16> : DestructionValueProtocol15<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15> {
    fun component16(): E16
}

interface DestructionValueProtocol17<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17> : DestructionValueProtocol16<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16> {
    fun component17(): E17
}

interface DestructionValueProtocol18<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18> : DestructionValueProtocol17<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17> {
    fun component18(): E18
}

interface DestructionValueProtocol19<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19> : DestructionValueProtocol18<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18> {
    fun component19(): E19
}

interface DestructionValueProtocol20<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20> : DestructionValueProtocol19<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19> {
    fun component20(): E20
}

interface DestructionValueProtocol21<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21> : DestructionValueProtocol20<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20> {
    fun component21(): E21
}

interface DestructionValueProtocol22<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22> : DestructionValueProtocol21<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21> {
    fun component22(): E22
}

interface DestructionValueProtocol23<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23> : DestructionValueProtocol22<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22> {
    fun component23(): E23
}

interface DestructionValueProtocol24<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24> : DestructionValueProtocol23<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23> {
    fun component24(): E24
}

interface DestructionValueProtocol25<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25> : DestructionValueProtocol24<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24> {
    fun component25(): E25
}

interface DestructionValueProtocol26<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26> : DestructionValueProtocol25<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25> {
    fun component26(): E26
}

interface DestructionValueProtocol27<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27> : DestructionValueProtocol26<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26> {
    fun component27(): E27
}

interface DestructionValueProtocol28<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27, out E28> : DestructionValueProtocol27<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27> {
    fun component28(): E28
}

interface DestructionValueProtocol29<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27, out E28, out E29> : DestructionValueProtocol28<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28> {
    fun component29(): E29
}

interface DestructionValueProtocol30<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27, out E28, out E29, out E30> : DestructionValueProtocol29<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29> {
    fun component30(): E30
}

interface DestructionValueProtocol31<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27, out E28, out E29, out E30, out E31> : DestructionValueProtocol30<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30> {
    fun component31(): E31
}

interface DestructionValueProtocol32<out E1, out E2, out E3, out E4, out E5, out E6, out E7, out E8, out E9, out E10, out E11, out E12, out E13, out E14, out E15, out E16, out E17, out E18, out E19, out E20, out E21, out E22, out E23, out E24, out E25, out E26, out E27, out E28, out E29, out E30, out E31, out E32> : DestructionValueProtocol31<E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31> {
    fun component32(): E32
}